name: Weekly Scrape and Compare

on:
  schedule:
    - cron: "0 8 * * 1" # Runs every Monday at 08:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.3"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t my-scraper-app .

      - name: Run Scraper
        run: |
          docker run --rm my-scraper-app --mode slow --timeout 60 > countries_new.json
          echo test >> countries_new.json
          cat countries_new.json >> $GITHUB_OUTPUT

      - name: Check if countries_new.json differs from countries.json
        id: check_diff
        run: |
          sudo apt-get -y install diffutils
          if ! diff -q countries_new.json countries.json > /dev/null; then
            echo "files differ"
            echo "::set-output name=files_differs::true"
          else
            echo "::set-output name=files_differs::false"
          fi

      - name: Replace countries.json with countries_new.json
        run: |
          mv countries_new.json countries.json
        if: steps.check_diff.outputs.files_differs == 'true'

      - name: Commit changes if countries.json differs
        id: commit_changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update countries.json"
          new_branch: update-countries-json
          add: 'countries.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        if: steps.check_diff.outputs.files_differs == 'true'

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GH_PAT }}
          source_branch: update-countries-json
          target_branch: main
          title: My pull request
          body: "**Automated pull request**"
          reviewer: detrin
          assignee: detrin
          label: updating
        if: steps.check_diff.outputs.files_differs == 'true'
